
export default {
    sounds: {
        hit1: new AudioClip("sounds/sounds_hit01.mp3"),
        hit2: new AudioClip("sounds/sounds_hit02.mp3"),
        hit3: new AudioClip("sounds/sounds_hit03.mp3"),
        ballhit1: new AudioClip("sounds/sounds_ballhit01.mp3"),
        ballhit2: new AudioClip("sounds/sounds_ballhit02.mp3"),
        ballhit3: new AudioClip("sounds/sounds_ballhit03.mp3"),
        pickup: new AudioClip("sounds/get_ready.mp3"),
        throw: new AudioClip("sounds/sounds_throw.mp3"),
        strike: new AudioClip("sounds/sounds_strike_spare.mp3"),
        spare: new AudioClip("sounds/sounds_strike_spare.mp3"),
        welcome: new AudioClip("sounds/welcome_player.mp3"),
    },
    models: {
        resetButton:new GLTFShape("models/scene/resetbutton.glb"), 
        bowlingPin: new GLTFShape("models/bowling/Pin.glb"),
        bowlingBall1: new GLTFShape("models/bowling/BowlingBall1.glb"),
        bowlingBall2: new GLTFShape("models/bowling/BowlingBall2.glb"),
        bowlingBall3: new GLTFShape("models/bowling/BowlingBall3.glb"),
    },
    textures: {
        powerMeter: new Texture("images/ui/power_bar.png"),
        swingMeter: new Texture("images/ui/swing_bar.png"),
        powerPointer: new Texture("images/ui/power_pointer.png"),
        swingPointer: new Texture("images/ui/swing_pointer.png"),
        strike: new Texture("images/ui/strike.png"),
        spare: new Texture("images/ui/spare.png"),
        scoreIcon: new Texture("images/ui/score_icon.png"),
        roundIcon: new Texture("images/ui/round_icon.png"),
    },
    scenery: {
        grass: new GLTFShape("models/scene/FloorBaseGrass_01.glb"),
        stone: new GLTFShape("models/scene/stoneGround.glb"),
        floor: new GLTFShape("models/scene/floorcollider2.glb"),
        logo: new GLTFShape("models/scene/pengball.glb"),
        pinkScreen: new GLTFShape("models/scene/pink screen.glb"),
        greenScreen: new GLTFShape("models/scene/green screen.glb"),
        building: new GLTFShape("models/scene/igloocolliderwdoors.glb"),
        iceBlock1: new GLTFShape("models/scene/iceonfloor1.glb"),
        iceBlock2: new GLTFShape("models/scene/iceonfloor2.glb"),
        iceBlock3: new GLTFShape("models/scene/iceonfloor3.glb"),
        iceGate: new GLTFShape("models/scene/oooice.glb"),
        board: new GLTFShape("models/scene/InfoBoard.glb"),
        billboard: new GLTFShape("models/scene/Billboard_Black.glb"),
        lights: new GLTFShape("models/scene/Garland_Curve_Blue_Purple.glb"),
        ballRack: new GLTFShape("models/scene/BALLRACK2.glb"),
        outOfOrder: new GLTFShape("models/scene/outoforder1.glb"),
        iceMan1: new GLTFShape("models/scene/45icemancollidersmirror.glb"),
        iceMan2: new GLTFShape("models/scene/-45icemancollidersmirror.glb"),
    }
}